#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSOR_GP2AP)	+= gp2ap002.o
obj-$(CONFIG_SENSOR_BMA250)	+= bma250_driver.o
obj-$(CONFIG_SENSOR_AMI306)	+= ami304.o
#
obj-$(CONFIG_SENSOR_KR3DH)	+= kr3dh.o
obj-$(CONFIG_SENSOR_AK8975)   	+= akm8975.o
obj-$(CONFIG_SENSOR_APDS9900) 	+= apds9900.o